### ISSUE TITLE
Implement a controller and listener in dart

### ISSUE THREAD

**Issue by bllaw** [erluxman/pdf_flutter#1]
Request a feature to have a controller to jump to a page using dart code.

Also a listener to report the current page number to let dart code react to it.

Feature to hide the ”1 of xxx" indicator for an easier internalisation, or provide a pattern/format/callback to display the string in different languages.

**Comment by erluxman** [comment]
Thanks for the PR, will look into it.

My main priority is to make it simple. If I can keep it simple and add features to it, I will definitely do it. 

If you ever get time before I do, feel free to make a PR.

**Comment by ASSASSIN-363** [comment]
Any update on this issue?

**Comment by erluxman** [comment]
YOu cannot as of now. Seems like I replied pretty quick 😀

sorry about that
