### ISSUE TITLE
Your link at " https://www.youtube.com/watch?v=xT654em3Lcs"  i.e   https://desiprogrammer.com/blogs/flutter-pdf is not opening

### ISSUE THREAD

**Issue by srk2k13** [erluxman/pdf_flutter#11]
I want to  use your  source code to upload pdf document  from phone storage or url or assets  mentioned in your youtube video.

But I ma unable to access your page    https://desiprogrammer.com/blogs/flutter-pdf.

saying as    

This site can’t be reached                         

[desiprogrammer.com](https://desiprogrammer.com/blogs/flutter-pdf) unexpectedly closed the connection.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_CLOSED

**Comment by erluxman** [comment]
That is a tutorial made on this library which I have no control of  and as of now that site is live.
