### ISSUE TITLE
Is there a way to get the coordinates of a tap event on a page?

### ISSUE THREAD

**Issue by GP4cK** [erluxman/pdf_flutter#13]
I would like to let the user add markers on the PDF. For that, I would need 2 things:

1. Being able to listen to tap events on the PDF to get a set of coordinates X and Y
2. Give the viewer a list of coordinates and some colors so that it can place the markers on top of the document

I understand that it may not be supported at the moment but may I have some indications on how to start if I had to implement this?
Thanks a lot!

**Comment by erluxman** [comment]
Right now there are no such feature and no promises. If you build something like that. Feel free to Make PR.
