### ISSUE TITLE
Is there a way to force light mode?

### ISSUE THREAD

**Issue by dcarriola** [erluxman/pdf_flutter#14]
Hi,

Somehow, every time the PDF loads, if I have activated the dark mode on my iPhone, the background is black and I would like to make it always white. I already tried on my side forcing light mode but the PDF viewer still gets my phone's mode.

Please, let me know if it's something from your side and how to solve it.

I'm using version ^1.1.3.

Thanks!

**Comment by erluxman** [comment]
I am afraid, no such feature is currently possible. 

Thanks for giving it a try.

**Comment by romreed** [comment]
i got same error. Any changes?
