### ISSUE TITLE
How to set the height to fill the reminding space?

### ISSUE THREAD

**Issue by zfc0812** [erluxman/pdf_flutter#20]
I have a button on my app and I would like to the pdf viewer to fill the reminding space. Because I have another button widget, so I can't use double.infinity for the height. I tried to wrapped the PDF widget in `Extended`, but it does not make it to fill the reminding height.

**Comment by devj3ns** [comment]
For me this works:

```
var size = MediaQuery.of(context).size;

PDF.network(
        url,
        height: size.height,
        width: size.width,
      );
```

It's not ideal but it works. Hopefully some day this plugin supports being wrapped in an Expanded Widget.

**Comment by erluxman** [comment]
Thanks for response @devj3ns
