### ISSUE TITLE
Dependencies conflict

### ISSUE THREAD

**Issue by DogeeeXD** [erluxman/pdf_flutter#28]
Hi, I encountered a problem that says:
`pdf_flutter 1.1.4 depends on http ^0.12.2 and no versions of pdf_flutter match >1.1.4 <2.0.0, pdf_flutter ^1.1.4 requires http ^0.12.2`
is it possible to update the http dependency to ^0.13.0?
As it is conflicting with alot of other packages.

**Comment by lovisaWilla** [comment]
@devj3ns looks like you already did this upgrade, but it never made it all the way to the latest release -> https://pub.dev/packages/pdf_flutter 🤷 @erluxman could you please look into this 🙏  we need to upgrade to flutter 2.0 and are super grateful of this work

**Comment by devj3ns** [comment]
> @devj3ns looks like you already did this upgrade, but it never made it all the way to the latest release -> https://pub.dev/packages/pdf_flutter 🤷 @erluxman could you please look into this 🙏 we need to upgrade to flutter 2.0 and are super grateful of this work

Yes, that's true, in the master this issue is fixed and the package is migrated to null safety. 

I am currently importing the package as a git dependency:
```
pdf_flutter:
    git: https://github.com/erluxman/pdf_flutter
```

**Comment by DogeeeXD** [comment]
@devj3ns Thanks for the fix, I'll close the issue.
It would be better if the update is pushed to pub.dev also.
