### ISSUE TITLE
Pdf Network error

### ISSUE THREAD

**Issue by ahmeterdgn** [erluxman/pdf_flutter#5]
It works in debug mode but not in release mode. I am having this problem when using pdf.network. How do I solve it? application is closing

**Comment by mirandaink01** [comment]
I have the same problem. Need help

**Comment by erluxman** [comment]
Let me check it, I think I had misunderstood  the previous issue,

I been pretty busy that I wasn't able to look into it. Sorry about that guys.

Will try to come up with a good news ASAP

**Comment by erluxman** [comment]
Dup of https://github.com/erluxman/pdf_flutter/issues/4

Let's discuss there
